### ISSUE TITLE
Assertion `loop->watchers[w->fd] == w' failed in uv__io_stop

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1247]
###### IoT.js version:

```
Checked revision: 9c1e57c
Build command: ./tools/build.py --buildtype=debug --target-arch=i686
```
###### OS:

```
Ubuntu 16.04.3 LTS
```
###### Test case:

```javascript
var net = require('net');
var fs = require('fs');
var http = require('http');

net.Server.prototype.listen(3982, Boolean.prototype.toString)
fs.closeSync(Function("return this")().i) 
http.createServer(Date.prototype.setSeconds).listen(Function("return this")().i, undefined)
```

###### Backtrace:

```
iotjs: iotjs/deps/libtuv/src/unix/core.c:768: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7842ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7844407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf783bd07 in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf783bd8b in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
#5  0x08153d67 in uv__io_stop (loop=0x821f140 <default_loop_struct>, w=0xf4b02d34, events=8197) at iotjs/deps/libtuv/src/unix/core.c:768
#6  0x081540e7 in uv__io_close (loop=0x821f140 <default_loop_struct>, w=0xf4b02d34) at iotjs/deps/libtuv/src/unix/core.c:781
#7  0x0816acf0 in uv__stream_close (handle=0xf4b02cfc) at iotjs/deps/libtuv/src/unix/stream.c:1635
#8  0x0816d035 in uv__tcp_close (handle=0xf4b02cfc) at iotjs/deps/libtuv/src/unix/tcp.c:394
#9  0x081506f8 in uv_close (handle=0xf4b02cfc, close_cb=0x808a3ad <iotjs_on_handle_closed>) at iotjs/deps/libtuv/src/unix/core.c:123
#10 0x0808a71c in iotjs_handlewrap_close (handlewrap=0xf4b02ce0, on_close_cb=0x8082cfb <AfterClose>) at iotjs/src/iotjs_handlewrap.c:110
#11 0x08083009 in Close (jhandler=0xffffac30) at iotjs/src/modules/iotjs_module_tcp.c:246
#12 0x08064aa3 in iotjs_native_dispatch_function (jfunc=4126212771, jthis=4132578099, jargv=0xffffae78, jargc=0) at iotjs/src/iotjs_binding.c:801
#13 0x080e72f1 in ecma_op_function_call (func_obj_p=0xf5f102a0, this_arg_value=4132578099, arguments_list_p=0xffffae78, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:371
#14 0x0812418c in opfunc_call (frame_ctx_p=0xffffaef0) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#15 0x0812e752 in vm_execute (frame_ctx_p=0xffffaef0, arg_p=0xffffb164, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#16 0x0812ecf4 in vm_run (bytecode_header_p=0xf4f02f80, this_binding_value=4132575731, lex_env_p=0xf6522490, is_eval_code=false, arg_list_p=0xffffb164, arg_list_len=2) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#17 0x080e7254 in ecma_op_function_call (func_obj_p=0xf5f111d0, this_arg_value=4132575731, arguments_list_p=0xffffb164, arguments_list_len=2) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#18 0x0812418c in opfunc_call (frame_ctx_p=0xffffb280) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#19 0x0812e752 in vm_execute (frame_ctx_p=0xffffb280, arg_p=0xffffb638, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#20 0x0812ecf4 in vm_run (bytecode_header_p=0xf3f01c80, this_binding_value=4132478259, lex_env_p=0xf650bdf0, is_eval_code=false, arg_list_p=0xffffb638, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#21 0x080e7254 in ecma_op_function_call (func_obj_p=0xf5f086b0, this_arg_value=4132478259, arguments_list_p=0xffffb638, arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#22 0x08137420 in ecma_builtin_function_prototype_object_call (this_arg=4126181043, arguments_list_p=0xffffb634, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
#23 0x08136d75 in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=36, this_arg_value=4126181043, arguments_list=0xffffb634, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:42
#24 0x080b6251 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_FUNCTION_PROTOTYPE, builtin_routine_id=36, this_arg_value=4126181043, arguments_list=0xffffb634, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
#25 0x080b6803 in ecma_builtin_dispatch_call (obj_p=0xf5f04780, this_arg_value=4126181043, arguments_list_p=0xffffb634, arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#26 0x080e7029 in ecma_op_function_call (func_obj_p=0xf5f04780, this_arg_value=4126181043, arguments_list_p=0xffffb634, arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:289
#27 0x0812418c in opfunc_call (frame_ctx_p=0xffffb6b0) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#28 0x0812e752 in vm_execute (frame_ctx_p=0xffffb6b0, arg_p=0xffffb914, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#29 0x0812ecf4 in vm_run (bytecode_header_p=0xf5501aa0, this_binding_value=4132478291, lex_env_p=0xf6505810, is_eval_code=false, arg_list_p=0xffffb914, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#30 0x080e7254 in ecma_op_function_call (func_obj_p=0xf5f06cd0, this_arg_value=4132478291, arguments_list_p=0xffffb914, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#31 0x0812418c in opfunc_call (frame_ctx_p=0xffffb9a0) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#32 0x0812e752 in vm_execute (frame_ctx_p=0xffffb9a0, arg_p=0xffffbbec, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#33 0x0812ecf4 in vm_run (bytecode_header_p=0xf6325340, this_binding_value=4126162179, lex_env_p=0xf6505810, is_eval_code=false, arg_list_p=0xffffbbec, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#34 0x080e7254 in ecma_op_function_call (func_obj_p=0xf5f06d60, this_arg_value=4126162179, arguments_list_p=0xffffbbec, arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#35 0x0812418c in opfunc_call (frame_ctx_p=0xffffbc60) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#36 0x0812e752 in vm_execute (frame_ctx_p=0xffffbc60, arg_p=0xffffbeac, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#37 0x0812ecf4 in vm_run (bytecode_header_p=0xf6103da0, this_binding_value=4126162179, lex_env_p=0xf6505810, is_eval_code=false, arg_list_p=0xffffbeac, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#38 0x080e7254 in ecma_op_function_call (func_obj_p=0xf5f06ca0, this_arg_value=4126162179, arguments_list_p=0xffffbeac, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#39 0x0812418c in opfunc_call (frame_ctx_p=0xffffbf20) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#40 0x0812e752 in vm_execute (frame_ctx_p=0xffffbf20, arg_p=0x0, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#41 0x0812ecf4 in vm_run (bytecode_header_p=0xf4f03d80, this_binding_value=4126149555, lex_env_p=0xf65007b0, is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#42 0x081238f6 in vm_run_global (bytecode_p=0xf4f03d80) at iotjs/deps/jerry/jerry-core/vm/vm.c:231
#43 0x0808f910 in jerry_run (func_val=4126151859) at iotjs/deps/jerry/jerry-core/api/jerry.c:451
#44 0x0805eab5 in iotjs_jhelper_eval (name=0x8184860 "iotjs.js", name_len=8, data=0x8192740 <iotjs_s> "/* Copyright 2015-present Samsung Electronics Co., Ltd. and other contributors\n *\n * Licensed under the Apache License, Version 2.0 (the \"License\");\n * you may not use this file except in compliance w"..., size=4261, strict_mode=false, throws=0xffffc130) at iotjs/src/iotjs_binding.c:472
#45 0x0805a4ed in iotjs_run (env=0x821e0a0 <current_env>) at iotjs/src/iotjs.c:103
#46 0x0805a6e8 in iotjs_start (env=0x821e0a0 <current_env>) at iotjs/src/iotjs.c:138
#47 0x0805aead in iotjs_entry (argc=3, argv=0xffffc374) at iotjs/src/iotjs.c:213
#48 0x08059ba6 in main (argc=3, argv=0xffffc374) at iotjs/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by glistening** [comment]
`Function("return this")().i` returns 6 from variable **i** defined in iotjs.js.
It forcibly close file descriptor that is used from other statement.
This assertion is valid for informing the developer that something wrong happens.
