### ISSUE TITLE
SIGABRT in uv__io_poll

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1251]
###### IoT.js version:

```
Checked revision: 9c1e57c
Build command: ./tools/build.py --buildtype=debug --target-arch=i686
```
###### OS:

```
Ubuntu 16.04.3 LTS
```
###### Test case:

```javascript
var http = require('http');
var http_common = require('http_common');
var fs = require('fs');

http.createServer(http_common.createHTTPParser().OnHeaders).listen(2450, 1);
fs.closeSync(keysLength);
```
The context of the abort call:
```c
    /* XXX Future optimization: do EPOLL_CTL_MOD lazily if we stop watching
     * events, skip the syscall and squelch the events after epoll_wait().
     */
    if (uv__epoll_ctl(loop->backend_fd, op, w->fd, &e)) {
      if (errno != EEXIST)
        abort();
```

###### Backtrace:

```
Program received signal SIGABRT, Aborted.
0xf7fd8be9 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7d98ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7d9a407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x080e44bc in uv__io_poll (loop=0x81276a0 <default_loop_struct>, timeout=-1)
    at iotjs/deps/libtuv/src/unix/linux-core.c:234
#4  0x080d9063 in uv_run (loop=0x81276a0 <default_loop_struct>, mode=UV_RUN_ONCE) at iotjs/deps/libtuv/src/unix/core.c:305
#5  0x08059b32 in iotjs_start (env=0x81274a0 <current_env>) at iotjs/src/iotjs.c:147
#6  0x08059e16 in iotjs_entry (argc=2, argv=0xffffc414) at iotjs/src/iotjs.c:213
#7  0x080596f6 in main (argc=2, argv=0xffffc414) at iotjs/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by glistening** [comment]
`keysLength` equals 6. (I find the definition in iotjs.js. It would be better to make `keysLength` invisible from user code.) Anyway, it seems that it closed the file descriptor that was used for http's listening, and epoll complains about it. I think it is application's bug, and calling abort() is reasonable.
