### ISSUE TITLE
Assertion '(uintptr_t) data_space_p % JMEM_ALIGNMENT == 0' failed in jmem_heap_alloc_block_internal

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1252]
###### IoT.js version:

```
Checked revision: 9c1e57c
Build command: ./tools/build.py --buildtype=debug --target-arch=i686
```
###### OS:

```
Ubuntu 16.04.3 LTS
```
###### Test case:
[Download test case](https://github.com/Samsung/iotjs/files/1362505/test.txt)

Note: the test case is pretty sensitive to changes. It can turn to flaky or produce other failures like:

```Assertion 'next_offset == JMEM_HEAP_END_OF_LIST || jmem_is_heap_pointer (JMEM_HEAP_GET_ADDR_FROM_OFFSET (next_offset))' failed at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c(jmem_heap_alloc_block_internal):258.```

or

```Assertion 'jmem_is_heap_pointer (ptr)' failed at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c(jmem_heap_free_block):436```

###### Backtrace:

```
ICE: Assertion '(uintptr_t) data_space_p % JMEM_ALIGNMENT == 0' failed at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c(jmem_heap_alloc_block_internal):317.
Error: ERR_FAILED_INTERNAL_ASSERTION

(gdb) bt
#0  jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at iotjs/deps/jerry/jerry-core/jrt/jrt-fatals.c:33
#1  0x080b2d4b in jerry_assert_fail (assertion=0x8108580 "(uintptr_t) data_space_p % JMEM_ALIGNMENT == 0", 
    file=0x81083ec "iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c", 
    function=0x81086c8 <__func__.3216> "jmem_heap_alloc_block_internal", line=317)
    at iotjs/deps/jerry/jerry-core/jrt/jrt-fatals.c:82
#2  0x080b248a in jmem_heap_alloc_block_internal (size=16) at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c:317
#3  0x080b24de in jmem_heap_gc_and_alloc_block (size=16, ret_null_on_error=false)
    at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c:360
#4  0x080b259b in jmem_heap_alloc_block (size=16) at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c:406
#5  0x080747be in ecma_alloc_property_pair () at iotjs/deps/jerry/jerry-core/ecma/base/ecma-alloc.c:242
#6  0x080777b7 in ecma_create_property (object_p=0x8160888 <jerry_global_heap+230952>, name_p=0x8160898 <jerry_global_heap+230968>, type_and_flags=17 '\021', 
    value=..., out_prop_p=0x0) at iotjs/deps/jerry/jerry-core/ecma/base/ecma-helpers.c:473
#7  0x08077a06 in ecma_create_named_data_property (object_p=0x8160888 <jerry_global_heap+230952>, name_p=0x8160898 <jerry_global_heap+230968>, 
    prop_attributes=16 '\020', out_prop_p=0x0) at iotjs/deps/jerry/jerry-core/ecma/base/ecma-helpers.c:559
#8  0x080aaa39 in ecma_op_create_mutable_binding (lex_env_p=0x8160888 <jerry_global_heap+230952>, name_p=0x8160898 <jerry_global_heap+230968>, 
    is_deletable=false) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-lex-env.c:136
#9  0x080d0ae5 in ecma_op_create_arguments_object (func_obj_p=0x812a290 <jerry_global_heap+8240>, lex_env_p=0x8160888 <jerry_global_heap+230952>, 
    arguments_list_p=0xfffeffd8, arguments_number=2, bytecode_data_p=0x812a348 <jerry_global_heap+8424>)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-objects-arguments.c:214
#10 0x080a91fc in ecma_op_function_call (func_obj_p=0x812a290 <jerry_global_heap+8240>, this_arg_value=135479827, arguments_list_p=0xfffeffd8, 
    arguments_list_len=2) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:344
#11 0x080c4919 in opfunc_call (frame_ctx_p=0xffff0004) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#12 0x080c91f8 in vm_execute (frame_ctx_p=0xffff0004, arg_p=0xffff022c, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#13 0x080c93bb in vm_run (bytecode_header_p=0x8133448 <jerry_global_heap+45544>, this_binding_value=135430779, lex_env_p=0x813dc30 <jerry_global_heap+88528>, 
    is_eval_code=false, arg_list_p=0xffff022c, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#14 0x080a922b in ecma_op_function_call (func_obj_p=0x8145500 <jerry_global_heap+119456>, this_arg_value=88, arguments_list_p=0xffff022c, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#15 0x080a94a4 in ecma_op_function_call (func_obj_p=0x814a230 <jerry_global_heap+139216>, this_arg_value=135662411, arguments_list_p=0xffff022c, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:429
#16 0x080c4919 in opfunc_call (frame_ctx_p=0xffff0254) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#17 0x080c91f8 in vm_execute (frame_ctx_p=0xffff0254, arg_p=0xffff03e8, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#18 0x080c93bb in vm_run (bytecode_header_p=0x8128c00 <jerry_global_heap+2464>, this_binding_value=135430859, lex_env_p=0x815e0a8 <jerry_global_heap+220744>, 
    is_eval_code=false, arg_list_p=0xffff03e8, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#19 0x080a922b in ecma_op_function_call (func_obj_p=0x8128740 <jerry_global_heap+1248>, this_arg_value=135430859, arguments_list_p=0xffff03e8, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#20 0x080c4919 in opfunc_call (frame_ctx_p=0xffff0414) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#21 0x080c91f8 in vm_execute (frame_ctx_p=0xffff0414, arg_p=0xffff05e0, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#22 0x080c93bb in vm_run (bytecode_header_p=0x812abf8 <jerry_global_heap+10648>, this_binding_value=135440027, lex_env_p=0x812a9e8 <jerry_global_heap+10120>, 
    is_eval_code=false, arg_list_p=0xffff05e0, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#23 0x080a922b in ecma_op_function_call (func_obj_p=0x812c0e0 <jerry_global_heap+16000>, this_arg_value=135440027, arguments_list_p=0xffff05e0, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#24 0x080c4919 in opfunc_call (frame_ctx_p=0xffff06a4) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#25 0x080c91f8 in vm_execute (frame_ctx_p=0xffff06a4, arg_p=0xffff0994, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#26 0x080c93bb in vm_run (bytecode_header_p=0x81633a8 <jerry_global_heap+241992>, this_binding_value=135591259, 
    lex_env_p=0x8133bc0 <jerry_global_heap+47456>, is_eval_code=false, arg_list_p=0xffff0994, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#27 0x080a922b in ecma_op_function_call (func_obj_p=0x8154530 <jerry_global_heap+180944>, this_arg_value=135591259, arguments_list_p=0xffff0994, 
    arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#28 0x080cdbb1 in ecma_builtin_function_prototype_object_call (this_arg=135611699, arguments_list_p=0xffff0990, arguments_number=4)
    at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
#29 0x080cd5d4 in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=36, this_arg_value=135611699, arguments_list=0xffff0990, 
    arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:42
#30 0x08087c9c in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_FUNCTION_PROTOTYPE, builtin_routine_id=36, this_arg_value=135611699, 
    arguments_list=0xffff0990, arguments_number=4)
    at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
#31 0x08088190 in ecma_builtin_dispatch_call (obj_p=0x812a460 <jerry_global_heap+8704>, this_arg_value=135611699, arguments_list_p=0xffff0990, 
    arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#32 0x080a90d6 in ecma_op_function_call (func_obj_p=0x812a460 <jerry_global_heap+8704>, this_arg_value=135611699, arguments_list_p=0xffff0990, 
    arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:289
#33 0x080c4919 in opfunc_call (frame_ctx_p=0xffff09c4) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#34 0x080c91f8 in vm_execute (frame_ctx_p=0xffff09c4, arg_p=0xffff0b70, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#35 0x080c93bb in vm_run (bytecode_header_p=0x812abd0 <jerry_global_heap+10608>, this_binding_value=135600811, lex_env_p=0x812a9e8 <jerry_global_heap+10120>, 
    is_eval_code=false, arg_list_p=0xffff0b70, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#36 0x080a922b in ecma_op_function_call (func_obj_p=0x812c0d0 <jerry_global_heap+15984>, this_arg_value=135600811, arguments_list_p=0xffff0b70, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#37 0x080c4919 in opfunc_call (frame_ctx_p=0xffff0bb4) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#38 0x080c91f8 in vm_execute (frame_ctx_p=0xffff0bb4, arg_p=0xffff0d48, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#39 0x080c93bb in vm_run (bytecode_header_p=0x812ab88 <jerry_global_heap+10536>, this_binding_value=135440027, lex_env_p=0x812a9e8 <jerry_global_heap+10120>, 
    is_eval_code=false, arg_list_p=0xffff0d48, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#40 0x080a922b in ecma_op_function_call (func_obj_p=0x812c0a0 <jerry_global_heap+15936>, this_arg_value=135440027, arguments_list_p=0xffff0d48, 
    arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#41 0x080c4919 in opfunc_call (frame_ctx_p=0xffff0d74) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#42 0x080c91f8 in vm_execute (frame_ctx_p=0xffff0d74, arg_p=0xffff0f40, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#43 0x080c93bb in vm_run (bytecode_header_p=0x812abf8 <jerry_global_heap+10648>, this_binding_value=135440027, lex_env_p=0x812a9e8 <jerry_global_heap+10120>, 
    is_eval_code=false, arg_list_p=0xffff0f40, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#44 0x080a922b in ecma_op_function_call (func_obj_p=0x812c0e0 <jerry_global_heap+16000>, this_arg_value=135440027, arguments_list_p=0xffff0f40, 
    arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#45 0x080c4919 in opfunc_call (frame_ctx_p=0xffff1004) at iotjs/deps/jerry/jerry-core/vm/vm.c:408
#46 0x080c91f8 in vm_execute (frame_ctx_p=0xffff1004, arg_p=0xffff12f4, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2743
#47 0x080c93bb in vm_run (bytecode_header_p=0x8160bb8 <jerry_global_heap+231768>, this_binding_value=135610907, 
    lex_env_p=0x8133b60 <jerry_global_heap+47360>, is_eval_code=false, arg_list_p=0xffff12f4, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2823
#48 0x080a922b in ecma_op_function_call (func_obj_p=0x8154130 <jerry_global_heap+179920>, this_arg_value=135610907, arguments_list_p=0xffff12f4, 
    arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:352
#49 0x080cdbb1 in ecma_builtin_function_prototype_object_call (this_arg=135610675, arguments_list_p=0xffff12f0, arguments_number=4)
    at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
#50 0x080cd5d4 in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=36, this_arg_value=135610675, arguments_list=0xffff12f0, 
    arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:42
.....
```
[Full backtrace](https://github.com/Samsung/iotjs/files/1362518/bt.txt)

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by zherczeg** [comment]
Is this iotjs specific or happens with JerryScript?

**Comment by renatahodovan** [comment]
The test case contains iotjs specific calls, hence JerryScript ends in a ReferenceError.

**Comment by glistening** [comment]
@renatahodovan After #1264 is landed, the test case for this issue does not work. It shows several errors:

```
uncaughtException: TypeError: Cannot read property 'length' of undefined
```

If I comment out line 56 to avoid error above, I got the following:
```
try { fz_globalObject["modules"].fs.rename("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", fz_glob    alObject["modules"].http.request({host: "127.0.0.1", method: "GET", port: fz_globalObject.keysLength}).socket.parser.OnHeadersComplete) } catch (err) { }
```

```
uncaughtException: Error: socket hang up
```

If I comment out line 58 to avoid `socket hang up ` error, I got another error.
However, I cannot re-produce the errors.
Could you make updated test case for current master branch?

**Comment by renatahodovan** [comment]
@glistening I cannot reproduce it anymore either. So it can be closed for now and will open another entry if I bump into it again.
