### ISSUE TITLE
Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed in ecma_free_string_list

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1463]
###### IoT.js version:

```
Checked revision: ab10ae5
Build command: tools/build.py --buildtype debug --jerry-profile=es2015-subset --experimental
```
###### OS:

```
Ubuntu 17.10, x86_64
```
###### Test case:

```javascript
function readfile(fileName) {
    return new Promise(function(resolve, reject) {
        throw function() {}(), Buffer;
    });
};

readfile(readfile).then(function(value) {
    loadfi([], 0);
}).prototype(function(e) {});
```

###### Backtrace:

```
ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):43.
Error: ERR_FAILED_INTERNAL_ASSERTION

(gdb) bt
#0  ecma_free_string_list (string_list_p=0x5555558b01d0 <jerry_global_heap+9360>) at iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c:43
#1  0x00005555555a7b57 in ecma_finalize_lit_storage () at iotjs/deps/jerry/jerry-core/ecma/base/ecma-literal-storage.c:60
#2  0x00005555555a65c5 in ecma_finalize () at iotjs/deps/jerry/jerry-core/ecma/base/ecma-init-finalize.c:65
#3  0x000055555557ee73 in jerry_cleanup () at iotjs/deps/jerry/jerry-core/api/jerry.c:219
#4  0x000055555557114c in iotjs_entry (argc=2, argv=0x7fffffffe178) at iotjs/src/iotjs.c:215
#5  0x00005555555708aa in main (argc=2, argv=0x7fffffffe178) at iotjs/src/platform/linux/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

**Comment by DanielBallaSZTE** [comment]
This issue was already fixed before in JerryScript.
I think it can be closed.
