### ISSUE TITLE
Assertion '!jerry_value_has_error_flag(jres)' failed in iotjs_jhelper_call_ok

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1482]
###### IoT.js version:

```
Checked revision: ab10ae5
Build command: tools/build.py --buildtype debug
```
###### OS:

```
Ubuntu 17.10, x86_64
```
###### Test case:

```javascript
var assert = require ( 'assert' ) ; 
process.on ('uncaughtException', function ( err ) { process += 'B' ; } ) ; 
process.on ('exit', function ( ) { } ) ; 
process.nextTick( function ( ) { assert . fail ( ) ; } ) ; 
assert.fail( ) ; 

```

###### Backtrace:

```
iotjs/src/iotjs_binding.c:279: Assertion '!jerry_value_has_error_flag(jres)' failed.

(gdb) bt
#0  iotjs_jhelper_call_ok (jfunc=2147, jthis=72, jargs=0x5555558893f0 <jargs_empty>)
    at iotjs/src/iotjs_binding.c:279
#1  0x000055555557039b in iotjs_process_next_tick () at iotjs/src/iotjs_binding_helper.c:88
#2  0x000055555556e98a in iotjs_start (env=0x555555889420 <current_env>) at iotjs/src/iotjs.c:136
#3  0x000055555556ed8c in iotjs_entry (argc=2, argv=0x7fffffffdd38) at iotjs/src/iotjs.c:204
#4  0x000055555556e58a in main (argc=2, argv=0x7fffffffdd38) at iotjs/src/platform/linux/iotjs_linux.c:19

```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

**Comment by DanielBallaSZTE** [comment]
This issue is a combination of #1360 and #1348, therefore #1495  and #1494 fixes it.

**Comment by DanielBallaSZTE** [comment]
The issue is fixed, so it can be closed now.
