### ISSUE TITLE
Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed in jmem_heap_finalize

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#1567]
###### IoT.js version:

```
Checked revision: 3244369
Build command: tools/build.py --clean --buildtype=debug --jerry-profile=es2015-subset
```
###### OS:

```
Ubuntu 17.10, x86_64
```
###### Test case:

```javascript
new Promise(new String().split, process._onUncaughtException(escape), URIError, process.env).then()
```

###### Backtrace:

```
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):181.
Error: ERR_FAILED_INTERNAL_ASSERTION
[Inferior 1 (process 26903) exited with code 0170]

Breakpoint 1, jmem_heap_finalize () at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c:181
181   JERRY_ASSERT (JERRY_CONTEXT (jmem_heap_allocated_size) == 0);
(gdb) bt
#0  jmem_heap_finalize () at iotjs/deps/jerry/jerry-core/jmem/jmem-heap.c:181
#1  0x00000000004c2887 in jmem_finalize () at iotjs/deps/jerry/jerry-core/jmem/jmem-allocator.c:51
#2  0x0000000000423a6c in jerry_cleanup () at iotjs/deps/jerry/jerry-core/api/jerry.c:226
#3  0x00000000004169e7 in iotjs_entry (argc=2, argv=0x7fffffffde68) at iotjs/src/iotjs.c:220
#4  0x00000000004160bd in main (argc=2, argv=0x7fffffffde68) at iotjs/src/platform/linux/iotjs_linux.c:19
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by DanielBallaSZTE** [comment]
This issue should be fixed with the newest jerry update.

**Comment by LaszloLango** [comment]
It works after the last JerryScript update.
