### ISSUE TITLE
./tools/build.py ValueError: Number of processes must be at least 1 Failed run_checktest

### ISSUE THREAD

**Issue by ysdafa** [Samsung/iotjs#203]
/home/ys/myGit/iotjs/tools/check_test.py /home/ys/myGit/iotjs/build/x86_64-linux/debug/iotjs/iotjs

[ run_pass ] Test Run

Traceback (most recent call last):
  File "/home/ys/myGit/iotjs/tools/check_test.py", line 276, in <module>
    if not test['handler'](iotjs):
  File "/home/ys/myGit/iotjs/tools/check_test.py", line 229, in run_pass_test
    passes, fails, skips = run_tests('run_pass', RUN_PASS_DIR)
  File "/home/ys/myGit/iotjs/tools/check_test.py", line 215, in run_tests
    pool = multiprocessing.Pool(processes = PROCESSES)
  File "/usr/lib/python3.4/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 161, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

Failed run_checktest

**Comment by ysdafa** [comment]
Sorry, I found the reason. For I running in virtualbox, the default CPU is set to 1. 
After change CPU to 2, the issue fixed.

**Comment by ILyoan** [comment]
@ysdafa Thanks for pointing this out!

This obviously is a bug.

We'll fix this.

**Comment by wateret** [comment]
Closing as #214 landed.
