### ISSUE TITLE
Assertion `!throws' failed in iotjs_jhelper_call_ok

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#648]
###### IoT.js version:

```
Checked revision: eec2ac9
Build: linux, x86_64, debug
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
(String = print *= print)()
```

###### Backtrace:

```
iotjs: iotjs/src/iotjs_binding.c:451: iotjs_jhelper_call_ok: Assertion `!throws' failed.
bt
#0  0x00007ffff7315428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff731702a in __GI_abort () at abort.c:89
#2  0x00007ffff730dbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x4b4a69 "!throws", file=file@entry=0x4b48a8 "iotjs/src/iotjs_binding.c", line=line@entry=451, function=function@entry=0x4b50d0 <__PRETTY_FUNCTION__.6689> "iotjs_jhelper_call_ok") at assert.c:92
#3  0x00007ffff730dc82 in __GI___assert_fail (assertion=0x4b4a69 "!throws", file=0x4b48a8 "iotjs/src/iotjs_binding.c", line=451, function=0x4b50d0 <__PRETTY_FUNCTION__.6689> "iotjs_jhelper_call_ok") at assert.c:101
#4  0x0000000000417b54 in iotjs_jhelper_call_ok (jfunc=0x7fffffffd070, jthis=0x6eb9e8 <modules+200>, jargs=0x7fffffffd090) at iotjs/src/iotjs_binding.c:451
#5  0x0000000000415108 in iotjs_uncaught_exception (jexception=0x7fffffffd100) at iotjs/src/iotjs_binding_helper.c:33
#6  0x0000000000414c27 in iotjs_run (process=0x6eb9e8 <modules+200>) at iotjs/src/iotjs.c:104
#7  0x0000000000414cca in iotjs_start (env=0x6eb8e0 <env>) at iotjs/src/iotjs.c:131
#8  0x0000000000414f44 in iotjs_entry (argc=2, argv=0x7fffffffd2b8) at iotjs/src/iotjs.c:191
#9  0x0000000000414956 in main (argc=2, argv=0x7fffffffd2b8) at iotjs/iotjs_linux.c:19
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by akosthekiss** [comment]
The following snippet has the same effect:
```js
String = NaN
throw null
```

The root cause is that the unhandled exception handler is implemented in JS (in iotjs.js) and is not allowed to throw exceptions. However, it does contain string manipulations (at least concatenation), and since `String` can be overwritten (e.g., with `NaN` in both test cases), those operations will fail and throw, which will lead to an assert.
