### ISSUE TITLE
Assertion `data != ((void *)0)' failed in iotjs_string_create_with_size

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#672]
###### IoT.js version:

```
Checked revision: 20cce20
Build command: ./tools/build.py --buildtype=debug --target-arch=i686 --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-cmake-param=-DJERRY_LIBC=OFF --jerry-cmake-param=-DFEATURE_SYSTEM_ALLOCATOR=ON --no-snapshot --no-check-valgrind
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
Buffer(new Array()).toString()
```

###### Backtrace:

```
_iotjs: iotjs/src/iotjs_string.c:39: iotjs_string_create_with_size: Assertion `data != ((void *)0)' failed.

Program received signal SIGABRT, Aborted.
0xf7fd8be9 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7843ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7845407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf783cd07 in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf783cd8b in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
#5  0x0808c93a in iotjs_string_create_with_size (data=0x0, size=0) at iotjs/src/iotjs_string.c:39
#6  0x0808163a in ToString (jhandler=0xffffac70) at iotjs/src/module/iotjs_module_buffer.c:444
#7  0x08067845 in iotjs_native_dispatch_function (jfunc=4128260771, jthis=4132487987, jargv=0xffffaee4, jargc=2)
    at iotjs/src/iotjs_binding.c:777
#8  0x080940ab in jerry_dispatch_external_function (function_object_p=0xf61042a0, handler_p=134641393, this_arg_value=4132487987, 
    arguments_list_p=0xffffaee4, arguments_list_len=2) at iotjs/deps/jerry/jerry-core/jerry.c:2065
#9  0x080e71a2 in ecma_op_function_call (func_obj_p=0xf61042a0, this_arg_value=4132487987, arguments_list_p=0xffffaee4, arguments_list_len=2)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
#10 0x081221e5 in opfunc_call (frame_ctx_p=0xffffaf50) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#11 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffaf50, arg_p=0xffffb198, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#12 0x0812c93d in vm_run (bytecode_header_p=0xf5905bc0, this_binding_value=4132488083, lex_env_p=0xf6505670, is_eval_code=false, arg_list_p=0xffffb198, 
    arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#13 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6103e50, this_arg_value=4132488083, arguments_list_p=0xffffb198, arguments_list_len=0)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#14 0x081221e5 in opfunc_call (frame_ctx_p=0xffffb200) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#15 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffb200, arg_p=0xffffb590, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#16 0x0812c93d in vm_run (bytecode_header_p=0xf5f07100, this_binding_value=4132483219, lex_env_p=0xf65007b0, is_eval_code=false, arg_list_p=0xffffb590, 
    arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#17 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6109010, this_arg_value=4132483219, arguments_list_p=0xffffb590, arguments_list_len=3)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#18 0x08135678 in ecma_builtin_function_prototype_object_call (this_arg=4128280595, arguments_list_p=0xffffb58c, arguments_number=4)
    at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
#19 0x08134fcd in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=36, this_arg_value=4128280595, arguments_list=0xffffb58c, 
    arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:51
#20 0x080b5890 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_FUNCTION_PROTOTYPE, builtin_routine_id=36, this_arg_value=4128280595, 
    arguments_list=0xffffb58c, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
#21 0x080b5e42 in ecma_builtin_dispatch_call (obj_p=0xf6104bd0, this_arg_value=4128280595, arguments_list_p=0xffffb58c, arguments_list_len=4)
    at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#22 0x080e6edb in ecma_op_function_call (func_obj_p=0xf6104bd0, this_arg_value=4128280595, arguments_list_p=0xffffb58c, arguments_list_len=4)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:461
#23 0x081221e5 in opfunc_call (frame_ctx_p=0xffffb600) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#24 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffb600, arg_p=0xffffb854, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#25 0x0812c93d in vm_run (bytecode_header_p=0xf5101a20, this_binding_value=4132483251, lex_env_p=0xf650c710, is_eval_code=false, arg_list_p=0xffffb854, 
    arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#26 0x080e7106 in ecma_op_function_call (func_obj_p=0xf61099a0, this_arg_value=4132483251, arguments_list_p=0xffffb854, arguments_list_len=0)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#27 0x081221e5 in opfunc_call (frame_ctx_p=0xffffb8c0) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#28 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffb8c0, arg_p=0xffffbafc, arg_list_len=3)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#29 0x0812c93d in vm_run (bytecode_header_p=0xf4f03e40, this_binding_value=4128265763, lex_env_p=0xf6507530, is_eval_code=false, arg_list_p=0xffffbafc, 
    arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#30 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6109a30, this_arg_value=4128265763, arguments_list_p=0xffffbafc, arguments_list_len=3)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#31 0x081221e5 in opfunc_call (frame_ctx_p=0xffffbb70) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#32 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffbb70, arg_p=0xffffbdb0, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#33 0x0812c93d in vm_run (bytecode_header_p=0xf5f03860, this_binding_value=4128265763, lex_env_p=0xf6507530, is_eval_code=false, arg_list_p=0xffffbdb0, 
    arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#34 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6109970, this_arg_value=4128265763, arguments_list_p=0xffffbdb0, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#35 0x081221e5 in opfunc_call (frame_ctx_p=0xffffbe20) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#36 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffbe20, arg_p=0xffffc058, arg_list_len=0)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#37 0x0812c93d in vm_run (bytecode_header_p=0xf5b01b40, this_binding_value=4128246659, lex_env_p=0xf6502670, is_eval_code=false, arg_list_p=0xffffc058, 
    arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#38 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6102110, this_arg_value=72, arguments_list_p=0xffffc058, arguments_list_len=0)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#39 0x081221e5 in opfunc_call (frame_ctx_p=0xffffc0d0) at iotjs/deps/jerry/jerry-core/vm/vm.c:391
#40 0x0812c3a7 in vm_execute (frame_ctx_p=0xffffc0d0, arg_p=0xf6502690, arg_list_len=1)
    at iotjs/deps/jerry/jerry-core/vm/vm.c:2661
#41 0x0812c93d in vm_run (bytecode_header_p=0xf4f03f40, this_binding_value=4128246659, lex_env_p=0xf6502670, is_eval_code=false, arg_list_p=0xf6502690, 
    arg_list_len=1) at iotjs/deps/jerry/jerry-core/vm/vm.c:2740
#42 0x080e7106 in ecma_op_function_call (func_obj_p=0xf6102170, this_arg_value=4128246659, arguments_list_p=0xf6502690, arguments_list_len=1)
    at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#43 0x0809355a in jerry_invoke_function (is_invoke_as_constructor=false, func_obj_val=4128252275, this_val=4128246659, args_p=0xf6502690, args_count=1)
    at iotjs/deps/jerry/jerry-core/jerry.c:1766
#44 0x08093602 in jerry_call_function (func_obj_val=4128252275, this_val=4128246659, args_p=0xf6502690, args_count=1)
    at iotjs/deps/jerry/jerry-core/jerry.c:1792
#45 0x0806205c in iotjs_jhelper_call (jfunc=0xffffc3b0, jthis=0x821bf40 <jglobal>, jargs=0xffffc430, throws=0xffffc370)
    at iotjs/src/iotjs_binding.c:430
#46 0x0805a029 in iotjs_run (process=0x821c0bc <modules+124>) at iotjs/src/iotjs.c:98
#47 0x0805a1e9 in iotjs_start (env=0x821bfc0 <env>) at iotjs/src/iotjs.c:131
#48 0x0805a696 in iotjs_entry (argc=2, argv=0xffffc5a4) at iotjs/src/iotjs.c:191
#49 0x08059996 in main (argc=2, argv=0xffffc5a4) at iotjs/iotjs_linux.c:19
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by glistening** [comment]
I've run the source and got the same call stack in current version. Thank you for reporting. We will investigate this issue and fix it.
