### ISSUE TITLE
SIGSEGV in iotjs_handlewrap_validate

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#717]
###### IoT.js version:

```
Checked revision: 393ed5f
Build command: ./tools/build.py --buildtype=debug --target-arch=i686 --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-cmake-param=-DJERRY_LIBC=OFF --jerry-cmake-param=-DFEATURE_SYSTEM_ALLOCATOR=ON --no-snapshot --no-check-valgrind --no-check-test 
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript

var net = require('net');

net.connect(1, "192.0.2.1").emit("end");

```

###### Backtrace:

```
ASAN:SIGSEGV
=================================================================
==21036==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x0808bf4a bp 0xffae7dd8 sp 0xffae7da0 T0)
    #0 0x808bf49 in iotjs_handlewrap_validate iotjs/src/iotjs_handlewrap.c:121
    #1 0x808afd2 in iotjs_handlewrap_from_jobject iotjs/src/iotjs_handlewrap.c:60
    #2 0x80820e9 in iotjs_tcpwrap_from_jobject iotjs/src/module/iotjs_module_tcp.c:60
    #3 0x8085729 in Connect iotjs/src/module/iotjs_module_tcp.c:325
    #4 0x8067634 in iotjs_native_dispatch_function iotjs/src/iotjs_binding.c:777
    #5 0x8093e34 in jerry_dispatch_external_function iotjs/deps/jerry/jerry-core/jerry.c:2065
    #6 0x80e6f8f in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
    #7 0x812232a in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:411
    #8 0x812c4cf in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2682
    #9 0x812ca65 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2761
    #10 0x80e6ef3 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #11 0x812232a in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:411
    #12 0x812c4cf in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2682
    #13 0x812ca65 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2761
    #14 0x80e6ef3 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #15 0x812232a in opfunc_call iotjs/deps/jerry/jerry-core/vm/vm.c:411
    #16 0x812c4cf in vm_execute iotjs/deps/jerry/jerry-core/vm/vm.c:2682
    #17 0x812ca65 in vm_run iotjs/deps/jerry/jerry-core/vm/vm.c:2761
    #18 0x80e6ef3 in ecma_op_function_call iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
    #19 0x80932e3 in jerry_invoke_function iotjs/deps/jerry/jerry-core/jerry.c:1766
    #20 0x809338b in jerry_call_function iotjs/deps/jerry/jerry-core/jerry.c:1792
    #21 0x8061e4b in iotjs_jhelper_call iotjs/src/iotjs_binding.c:430
    #22 0x805b123 in iotjs_make_callback_with_result iotjs/src/iotjs_binding_helper.c:109
    #23 0x805afca in iotjs_make_callback iotjs/src/iotjs_binding_helper.c:98
    #24 0x8071a62 in AfterGetAddrInfo iotjs/src/module/iotjs_module_dns.c:101
    #25 0x815c1b6 in uv__getaddrinfo_done iotjs/deps/libtuv/src/unix/getaddrinfo.c:156
    #26 0x81794fa in uv__work_done iotjs/deps/libtuv/src/threadpool.c:261
    #27 0x814d2f7 in uv__async_event iotjs/deps/libtuv/src/unix/async.c:122
    #28 0x814d72b in uv__async_io iotjs/deps/libtuv/src/unix/async.c:162
    #29 0x817738f in uv__io_poll iotjs/deps/libtuv/src/unix/linux-core.c:389
    #30 0x814f167 in uv_run iotjs/deps/libtuv/src/unix/core.c:303
    #31 0x8059ffe in iotjs_start iotjs/src/iotjs.c:138
    #32 0x805a485 in iotjs_entry iotjs/src/iotjs.c:191
    #33 0x8059785 in main iotjs/iotjs_linux.c:19
    #34 0xf6f3e636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #35 0x8059690  (iotjs/build/i686-linux/debug/bin/iotjs+0x8059690)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV iotjs/src/iotjs_handlewrap.c:121 iotjs_handlewrap_validate
==21036==ABORTING

```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by daeyeon** [comment]
```
Checked revision: 9d19b91
Build command: ./tools/build.py --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --no-snap
shot --no-check-valgrind --no-check-test --clean
```

It looks fixed. The error doesn't occur any longer.

**Comment by daeyeon** [comment]
This isn't reproduced in the lastest.
