### ISSUE TITLE
Assertion `iotjs_jval_is_object(jbuiltin)' failed in iotjs_bufferwrap_from_jbuiltin

### ISSUE THREAD

**Issue by renatahodovan** [Samsung/iotjs#718]
###### IoT.js version:

```
Checked revision: 393ed5f
Build command: ./tools/build.py --buildtype=debug --target-arch=i686 --compile-flag=-fsanitize=address --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-cmake-param=-DJERRY_LIBC=OFF --jerry-cmake-param=-DFEATURE_SYSTEM_ALLOCATOR=ON --no-snapshot --no-check-valgrind --no-check-test 
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript

var net = require('net');

net.connect(156, "192.0.2.1")._write(function() {}, function() {}, function() {})

```

###### Backtrace:

```
iotjs: iotjs/src/module/iotjs_module_buffer.c:61: iotjs_bufferwrap_from_jbuiltin: Assertion `iotjs_jval_is_object(jbuiltin)' failed.
bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7843ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7845407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf783cd07 in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf783cd8b in __assert_fail () from /lib/i386-linux-gnu/libc.so.6
#5  0x0806ad0c in iotjs_bufferwrap_from_jbuiltin (jbuiltin=0xffffad70) at iotjs/src/module/iotjs_module_buffer.c:61
#6  0x0806ae34 in iotjs_bufferwrap_from_jbuffer (jbuffer=0xf611ae30) at iotjs/src/module/iotjs_module_buffer.c:73
#7  0x080866aa in Write (jhandler=0xffffb010) at iotjs/src/module/iotjs_module_tcp.c:450
#8  0x08067635 in iotjs_native_dispatch_function (jfunc=4128319859, jthis=4132558547, jargv=0xffffb288, jargc=2) at iotjs/src/iotjs_binding.c:777
#9  0x08093e35 in jerry_dispatch_external_function (function_object_p=0xf6112970, handler_p=134640865, this_arg_value=4132558547, arguments_list_p=0xffffb288, arguments_list_len=2) at iotjs/deps/jerry/jerry-core/jerry.c:2065
#10 0x080e6f90 in ecma_op_function_call (func_obj_p=0xf6112970, this_arg_value=4132558547, arguments_list_p=0xffffb288, arguments_list_len=2) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:543
#11 0x0812232b in opfunc_call (frame_ctx_p=0xffffb300) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#12 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffb300, arg_p=0xffffb564, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#13 0x0812ca66 in vm_run (bytecode_header_p=0xf590e200, this_binding_value=4132555315, lex_env_p=0xf651df90, is_eval_code=false, arg_list_p=0xffffb564, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#14 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6112490, this_arg_value=4132555315, arguments_list_p=0xffffb564, arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#15 0x0812232b in opfunc_call (frame_ctx_p=0xffffb670) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#16 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffb670, arg_p=0xffffba00, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#17 0x0812ca66 in vm_run (bytecode_header_p=0xf3503c80, this_binding_value=4132483187, lex_env_p=0xf650d590, is_eval_code=false, arg_list_p=0xffffba00, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#18 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6109dc0, this_arg_value=4132483187, arguments_list_p=0xffffba00, arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#19 0x081357a1 in ecma_builtin_function_prototype_object_call (this_arg=4128284099, arguments_list_p=0xffffb9fc, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.c:206
#20 0x081350f6 in ecma_builtin_function_prototype_dispatch_routine (builtin_routine_id=36, this_arg_value=4128284099, arguments_list=0xffffb9fc, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-function-prototype.inc.h:42
#21 0x080b56c3 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_FUNCTION_PROTOTYPE, builtin_routine_id=36, this_arg_value=4128284099, arguments_list=0xffffb9fc, arguments_number=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:108
#22 0x080b5c75 in ecma_builtin_dispatch_call (obj_p=0xf61050b0, this_arg_value=4128284099, arguments_list_p=0xffffb9fc, arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
#23 0x080e6cc9 in ecma_op_function_call (func_obj_p=0xf61050b0, this_arg_value=4128284099, arguments_list_p=0xffffb9fc, arguments_list_len=4) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:461
#24 0x0812232b in opfunc_call (frame_ctx_p=0xffffba70) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#25 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffba70, arg_p=0xffffbcc4, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#26 0x0812ca66 in vm_run (bytecode_header_p=0xf5101aa0, this_binding_value=4132483219, lex_env_p=0xf650cf70, is_eval_code=false, arg_list_p=0xffffbcc4, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#27 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6108890, this_arg_value=4132483219, arguments_list_p=0xffffbcc4, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#28 0x0812232b in opfunc_call (frame_ctx_p=0xffffbd30) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#29 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffbd30, arg_p=0xffffbf6c, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#30 0x0812ca66 in vm_run (bytecode_header_p=0xf4f03e40, this_binding_value=4128267251, lex_env_p=0xf65074d0, is_eval_code=false, arg_list_p=0xffffbf6c, arg_list_len=3) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#31 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6108920, this_arg_value=4128267251, arguments_list_p=0xffffbf6c, arguments_list_len=3) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#32 0x0812232b in opfunc_call (frame_ctx_p=0xffffbfe0) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#33 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffbfe0, arg_p=0xffffc220, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#34 0x0812ca66 in vm_run (bytecode_header_p=0xf5f03860, this_binding_value=4128267251, lex_env_p=0xf65074d0, is_eval_code=false, arg_list_p=0xffffc220, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#35 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6108860, this_arg_value=4128267251, arguments_list_p=0xffffc220, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#36 0x0812232b in opfunc_call (frame_ctx_p=0xffffc290) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#37 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffc290, arg_p=0xffffc4c8, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#38 0x0812ca66 in vm_run (bytecode_header_p=0xf5b01b40, this_binding_value=4128246659, lex_env_p=0xf65024d0, is_eval_code=false, arg_list_p=0xffffc4c8, arg_list_len=0) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#39 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6102320, this_arg_value=72, arguments_list_p=0xffffc4c8, arguments_list_len=0) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#40 0x0812232b in opfunc_call (frame_ctx_p=0xffffc540) at iotjs/deps/jerry/jerry-core/vm/vm.c:411
#41 0x0812c4d0 in vm_execute (frame_ctx_p=0xffffc540, arg_p=0xf65024f0, arg_list_len=1) at iotjs/deps/jerry/jerry-core/vm/vm.c:2682
#42 0x0812ca66 in vm_run (bytecode_header_p=0xf4f03f40, this_binding_value=4128246659, lex_env_p=0xf65024d0, is_eval_code=false, arg_list_p=0xf65024f0, arg_list_len=1) at iotjs/deps/jerry/jerry-core/vm/vm.c:2761
#43 0x080e6ef4 in ecma_op_function_call (func_obj_p=0xf6102380, this_arg_value=4128246659, arguments_list_p=0xf65024f0, arguments_list_len=1) at iotjs/deps/jerry/jerry-core/ecma/operations/ecma-function-object.c:524
#44 0x080932e4 in jerry_invoke_function (is_invoke_as_constructor=false, func_obj_val=4128252803, this_val=4128246659, args_p=0xf65024f0, args_count=1) at iotjs/deps/jerry/jerry-core/jerry.c:1766
#45 0x0809338c in jerry_call_function (func_obj_val=4128252803, this_val=4128246659, args_p=0xf65024f0, args_count=1) at iotjs/deps/jerry/jerry-core/jerry.c:1792
#46 0x08061e4c in iotjs_jhelper_call (jfunc=0xffffc820, jthis=0x8222940 <jglobal>, jargs=0xffffc8a0, throws=0xffffc7e0) at iotjs/src/iotjs_binding.c:430
#47 0x08059e19 in iotjs_run (process=0x8222abc <modules+124>) at iotjs/src/iotjs.c:98
#48 0x08059fd9 in iotjs_start (env=0x82229c0 <current_env>) at iotjs/src/iotjs.c:131
#49 0x0805a486 in iotjs_entry (argc=2, argv=0xffffca14) at iotjs/src/iotjs.c:191
#50 0x08059786 in main (argc=2, argv=0xffffca14) at iotjs/iotjs_linux.c:19
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by hs0225** [comment]
`_write` is the private function. `write` which is the public function checks the type of the parameter. Therefore, the first parameter must be `Buffer`.(`String` can also be the first parameter. The string is converted to a buffer.)

**Comment by akosthekiss** [comment]
@hs0225 In JavaScript, traditional visibility categories don't exist. `_write` is just as much available to anyone as `write` is. Therefore, should a malevolent user intentionally call `_write` directly with an intentionally malformed first parameter, they may crash the framework. IMO, JS code may never be able to cause a crash in the C code. (Note: whenever argument validation happens on JS side only when native functions are called, this threat exists.)
