### ISSUE TITLE
Wrong and insufficient error message

### ISSUE THREAD

**Issue by daeyeon** [Samsung/iotjs#846]
a) Bug. The error message always says that the column, 38, is wrong even when the given code is wrong from the very first line.

```
const a;
-> uncaughtException: SyntaxError: Primary expression expected. [line: 1, column: 38]
```

b) In comparison with Javascript, developers will feel hard to fast debug in the below cases.

Case i)
```
var case1; unknown;
```

```diff
+++ NodeJS +++
// var test; unknown;
// ^
// ReferenceError: unknown is not defined
// at Object. (/home/daeyeon/Code/daeyeon.iotjs/test/tmp/test.js:5:11)
```

```diff
--- IoTJs, Jerry(--error-messages=on) ---
// uncaughtException: ReferenceError: unknown is not defined
```

Case ii)
```
var case2 = {};
case2.any();
```

```diff
+++ NodeJS +++
// home/daeyeon/Code/samsung.iotjs/tmp/error.js:24
// case2.any();
      ^
TypeError: case2.any is not a function
    at Object.<anonymous> (/home/daeyeon/Code/samsung.iotjs/tmp/error.js:24:7)
```

```diff
--- IoTJs, Jerry(--error-messages=on) ---
// uncaughtException: TypeError: Expected a function.
```

Of course, there are a lot unkind messages pending improvement. These look very essential. Especially, the case ii will get users frustrated because the clue may be too broad to find. Improving this seems important in usability perspective.

**Comment by LaszloLango** [comment]
It is more like a feature request than a bug. :) For parse errors there are location information. The default command line application in JerryScript gives a similar output as NodeJS. I think we can do it in IoT.js easily. At the moment you must use the debugger to track down runtime exceptions.

**Comment by daeyeon** [comment]
Yes, someone who well knows the glue layer b/t JerryScript and IoT.js would fix this easily. I just wanted his help. :) I ran JerryScript CLI in bin/jerry with `--log-level 3`, and it's built with `error-messages=on`. In my observation, the messages aren't similar with NodeJS, but same with iot.js. I can't find other options.

**Comment by kolipka** [comment]
@LaszloLango There is a bug (column is invalid) and feature missing (no proper runtime errors)
As for debugger - it's usability is far, far behind the tools known from nodejs / browsers. I've started investigation of VSCode debugger interface to move it to real IDE.
I've started also initial work on REPL for IoT.js - I hope it would be helpful too.

**Comment by LaszloLango** [comment]
@kolipka REPL is a good idea. I was thinking on that too.

**Comment by yichoi** [comment]
@kolipka That's good however I have not confirmed the plan for REPL for IoT.js yet

**Comment by zherczeg** [comment]
JerryScript is designed for resource constrained devices, and key factor of memory optimization is throwing away as much information as possible to save more memory. However the debugger has no such limitations so JerryScript can send data such as line information for preservation. The debugger is capable of capturing exceptions, please check this example:

https://github.com/jerryscript-project/jerryscript/blob/master/tests/debugger/do_exception.js
https://github.com/jerryscript-project/jerryscript/blob/master/tests/debugger/do_exception.expected

Unlike simple error messages you can even inspect variables to figure out what happened. I think the debugger is quite a powerful tool which we can be proud of.

**Comment by glistening** [comment]
IMHO, if we can turn on the descriptive and more helpful error messages in debug mode, and the device itself is capable of the rich error message feature, it would be nice to support this feature. Because IoT.js users don't need to set up and learn how to use the IoT.js/JerryScript debugger. However, for now, we are supposed to release IoT.js 1.0 in June. So I want to put off this discussion till release.
